-- PostgreSQL schema for the attendance system.
-- Create the database separately if needed:
--   CREATE DATABASE asistencia_db;

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  usuario VARCHAR(60) NOT NULL UNIQUE,
  pass_hash VARCHAR(255) NOT NULL,
  rol VARCHAR(20) NOT NULL DEFAULT 'viewer' CHECK (rol IN ('admin', 'registro', 'viewer')),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS asistentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dni VARCHAR(15) NOT NULL UNIQUE,
  nombres VARCHAR(120) NOT NULL,
  apellidos VARCHAR(120) NOT NULL,
  mesa VARCHAR(50) NOT NULL DEFAULT '',
  area VARCHAR(120),
  cargo VARCHAR(120),
  deuda VARCHAR(2) NOT NULL DEFAULT 'NO' CHECK (deuda IN ('SI', 'NO')),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(180) NOT NULL,
  descripcion VARCHAR(255),
  lugar VARCHAR(180),
  fecha DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fin TIME,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS asistencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
  asistente_id BIGINT NOT NULL REFERENCES asistentes(id) ON DELETE CASCADE,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'PRESENTE' CHECK (estado IN ('PRESENTE', 'TARDE')),
  registrado_por BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  obs VARCHAR(255),
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_asistencia_evento UNIQUE (evento_id, asistente_id)
);

INSERT INTO usuarios (nombre, usuario, pass_hash, rol, activo)
VALUES ('Administrador', 'admin', '$2y$10$k4m1bQ8xB7B5y3R1GkY0hO3Rjv8TRaQm7gJk8cYB4Qh0j1m3yKQeK', 'admin', TRUE)
ON CONFLICT (usuario) DO NOTHING;

-- Default credentials:
-- user: admin
-- password: admin123
