-- PostgreSQL migration for installations that had the old schema without events.
-- Run this against the asistencia_db database.

CREATE TABLE IF NOT EXISTS eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(180) NOT NULL,
  descripcion VARCHAR(255),
  lugar VARCHAR(180),
  fecha DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fin TIME,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE asistencias
  ADD COLUMN IF NOT EXISTS evento_id BIGINT;

DO $$
DECLARE
  evt_id BIGINT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM eventos) THEN
    INSERT INTO eventos (titulo, descripcion, lugar, fecha, hora_inicio, hora_fin, activo, creado_por)
    VALUES (
      'Asistencia General',
      'Evento creado por migracion',
      NULL,
      CURRENT_DATE,
      '08:00:00',
      NULL,
      TRUE,
      (SELECT id FROM usuarios WHERE usuario = 'admin' LIMIT 1)
    );
  END IF;

  SELECT id INTO evt_id FROM eventos ORDER BY id ASC LIMIT 1;
  UPDATE asistencias SET evento_id = evt_id WHERE evento_id IS NULL;
END $$;

ALTER TABLE asistencias
  ALTER COLUMN evento_id SET NOT NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'uq_asistencia_dia'
  ) THEN
    ALTER TABLE asistencias DROP CONSTRAINT uq_asistencia_dia;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'uq_asistencia_evento'
  ) THEN
    ALTER TABLE asistencias
      ADD CONSTRAINT uq_asistencia_evento UNIQUE (evento_id, asistente_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_asist_evento'
  ) THEN
    ALTER TABLE asistencias
      ADD CONSTRAINT fk_asist_evento FOREIGN KEY (evento_id) REFERENCES eventos(id) ON DELETE CASCADE;
  END IF;
END $$;
